"""
Apply PDF-verified lesson data from lessons_index.json:
  1. Update every lesson title in data.js (en/tr/ar) to the PDF-verified version
  2. Swap L1 Week 6 ↔ L1 Week 7 question arrays (PDF revealed they were inverted)
  3. Emit portal/lessons_index.js with LESSON_INDEX usable from the browser

Idempotent: safe to re-run.
"""

import json
import re
from pathlib import Path

ROOT = Path(__file__).parent
INDEX_FILE = ROOT / "lessons_index.json"
DATA_JS = ROOT / "data.js"
OUT_JS = ROOT / "lessons_index.js"


def js_quote(s):
    return s.replace("\\", "\\\\").replace("'", "\\'")


def main():
    index = json.loads(INDEX_FILE.read_text())
    text = DATA_JS.read_text()

    # ── 1. Replace each lesson title block ─────────────────────────────────
    # Match a `week: N, pdf: 'Level-X/...'` followed by a title block, where
    # the level/week tells us which index entry to use.
    pattern = re.compile(
        r"(week:\s*(\d+)\s*,\s*pdf:\s*'(Level-(\d+)/[^']+)'\s*,\s*\n?\s*title:\s*\{)"
        r"\s*en:\s*'(?:[^'\\]|\\.)*'\s*,\s*"
        r"tr:\s*'(?:[^'\\]|\\.)*'\s*,\s*"
        r"ar:\s*'(?:[^'\\]|\\.)*'\s*\}",
        re.DOTALL,
    )

    updated = 0

    def repl(m):
        nonlocal updated
        prefix = m.group(1)
        week_in_data = int(m.group(2))
        level = int(m.group(4))
        # week_in_data is the per-level week (1..14)
        key = f"L{level}W{week_in_data}"
        if key not in index:
            return m.group(0)
        v = index[key]["verified_title"]
        updated += 1
        return (
            f"{prefix} en: '{js_quote(v['en'])}', "
            f"tr: '{js_quote(v['tr'])}', "
            f"ar: '{js_quote(v['ar'])}' }}"
        )

    text = pattern.sub(repl, text)
    print(f"  ✓ updated {updated} lesson titles")

    # ── 2. Swap L1 Week 6 ↔ Week 7 question blocks ──────────────────────────
    # Find each lesson block by its `week: N, pdf: 'Level-1/Nth Lesson...'`
    # marker and grab its full questions array.
    def lesson_block_regex(week_n, lesson_n_str):
        return re.compile(
            r"(week:\s*" + str(week_n) + r"\s*,\s*pdf:\s*'Level-1/" + lesson_n_str
            + r"[^']+'.*?questions:\s*\[)(.*?)(\]\s*\n?\s*\})",
            re.DOTALL,
        )

    re6 = lesson_block_regex(6, "6th")
    re7 = lesson_block_regex(7, "7th")
    m6 = re6.search(text)
    m7 = re7.search(text)
    if m6 and m7:
        q6 = m6.group(2)
        q7 = m7.group(2)
        # Idempotency check: if W6 questions already contain detached-pronoun
        # markers (هُوَ, هِيَ, إِيَّاكَ, أَنْتِ), the swap was already done.
        already_swapped = any(t in q6 for t in ["إِيَّاكَ", "أَنْتِ", "هُنَّ"])
        if not already_swapped:
            text2 = re6.sub(lambda m: m.group(1) + q7 + m.group(3), text, count=1)
            text2 = re7.sub(lambda m: m.group(1) + q6 + m.group(3), text2, count=1)
            text = text2
            print("  ✓ swapped L1 W6 ↔ W7 question arrays (PDF says they were inverted)")
        else:
            print("  • W6/W7 already swapped — skipping")
    else:
        print("  ⚠️  could not find both W6 and W7 question blocks; skipped swap")

    DATA_JS.write_text(text)

    # ── 3. Emit lessons_index.js ────────────────────────────────────────────
    js_lines = [
        "// Auto-generated by apply_lesson_index.py from lessons_index.json",
        "// Source-of-truth grammar concept index built from the 42 lesson PDFs.",
        f"const LESSON_INDEX = {json.dumps(index, ensure_ascii=False, indent=2)};",
    ]
    OUT_JS.write_text("\n".join(js_lines) + "\n")
    print(f"  ✓ wrote {OUT_JS.name} ({len(index)} lessons)")


if __name__ == "__main__":
    main()
