"""
Build a vocabulary pool from extracted PDF text using Claude.

Input:  portal/vocab_raw/*.txt  (one file per source PDF)
Output: portal/vocab.js         (one JS array of {ar, tr, en, source} entries)

Run with:
  export ANTHROPIC_API_KEY=...
  cd portal && venv/bin/python build_vocab.py
"""

import os
import json
import re
import sys
import time
from pathlib import Path
import anthropic

ROOT = Path(__file__).parent
RAW_DIR = ROOT / "vocab_raw"
OUT_FILE = ROOT / "vocab.js"
CACHE_FILE = ROOT / "vocab_cache.json"

PROMPT_TEMPLATE = """You are extracting Arabic vocabulary from Turkish learning material.

Below is text extracted from a PDF (formatting is broken — Arabic and Turkish are interleaved out of order). Find every Arabic word/phrase that has a Turkish translation, and output one JSON line per pair.

Output ONLY a JSON array. Each entry must be:
{{ "ar": "<Arabic word with diacritics>", "tr": "<Turkish meaning>", "en": "<English meaning, you translate>" }}

Rules:
- Skip headings, page numbers, surah names, lesson titles
- For verbs given as "past form / present form" (e.g. "كَتَبَ يَكْتُبُ"), keep both in `ar`
- If a Turkish meaning has multiple alternatives separated by "/", keep them
- Translate Turkish → English yourself, briefly (1–4 words)
- Skip duplicates within this file
- If you can't read it cleanly, skip the entry rather than guess

Source filename: {filename}

Text:
---
{text}
---

Return ONLY the JSON array, no prose."""


def load_cache():
    if CACHE_FILE.exists():
        return json.loads(CACHE_FILE.read_text())
    return {}


def save_cache(cache):
    CACHE_FILE.write_text(json.dumps(cache, ensure_ascii=False, indent=2))


def extract_pairs(client, text, filename):
    if not text.strip():
        return []
    if len(text) > 18000:
        text = text[:18000]
    prompt = PROMPT_TEMPLATE.format(filename=filename, text=text)
    msg = client.messages.create(
        model="claude-sonnet-4-6",
        max_tokens=8000,
        messages=[{"role": "user", "content": prompt}],
    )
    raw = msg.content[0].text.strip()
    # Strip code fences if present
    raw = re.sub(r"^```(?:json)?\s*", "", raw)
    raw = re.sub(r"\s*```$", "", raw)
    try:
        return json.loads(raw)
    except json.JSONDecodeError:
        # Try to find array bounds
        start = raw.find("[")
        end = raw.rfind("]")
        if start >= 0 and end > start:
            try:
                return json.loads(raw[start : end + 1])
            except json.JSONDecodeError:
                pass
        print(f"  ⚠️  Could not parse JSON from {filename}", file=sys.stderr)
        return []


def main():
    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key:
        print("ERROR: set ANTHROPIC_API_KEY", file=sys.stderr)
        sys.exit(1)

    client = anthropic.Anthropic(api_key=api_key)
    cache = load_cache()
    txt_files = sorted(RAW_DIR.glob("*.txt"))
    print(f"📚 {len(txt_files)} source files; {len(cache)} already cached")

    all_entries = []
    for i, txt_path in enumerate(txt_files, 1):
        fname = txt_path.stem
        if fname in cache:
            entries = cache[fname]
            print(f"[{i}/{len(txt_files)}] {fname}  (cached: {len(entries)} entries)")
        else:
            text = txt_path.read_text()
            print(f"[{i}/{len(txt_files)}] {fname}  extracting...", end=" ", flush=True)
            try:
                entries = extract_pairs(client, text, fname)
                print(f"{len(entries)} entries")
                cache[fname] = entries
                save_cache(cache)
                time.sleep(0.5)
            except Exception as e:
                print(f"FAILED: {e}")
                continue
        for entry in entries:
            entry_with_source = {**entry, "source": fname}
            all_entries.append(entry_with_source)

    # Deduplicate by Arabic
    seen = {}
    for e in all_entries:
        ar = e.get("ar", "").strip()
        if not ar:
            continue
        if ar not in seen:
            seen[ar] = e
    deduped = list(seen.values())

    print(f"\n✅ {len(all_entries)} raw entries → {len(deduped)} unique")

    js_content = (
        "// Auto-generated by build_vocab.py from PDFs in Kuran-Kerim Arapcasi/Words/\n"
        "// Each entry: { ar: Arabic, tr: Turkish, en: English, source: PDF stem }\n"
        f"const VOCAB_POOL = {json.dumps(deduped, ensure_ascii=False, indent=2)};\n"
    )
    OUT_FILE.write_text(js_content)
    print(f"📝 wrote {OUT_FILE}")


if __name__ == "__main__":
    main()
